const express = require('express')
const {verifyAdmin}=require('../middlewares/admin.auth.js')
const router=express.Router()
const adminControllers=require('../controllers/admin.controllers.js')
const {upload}=require('../middlewares/multer.uploadpfp.js')
router.get('/',verifyAdmin,adminControllers.adminIndex)
router.post("/register", adminControllers.adminRegister)
router.post("/login", adminControllers.adminLogin)
router.get('/logout',verifyAdmin,adminControllers.adminLogout)
router.get('/refreshToken',adminControllers.refreshAccessToken)
router.post('/upload-admin-profile',verifyAdmin,upload.single('userProfile'),adminControllers.updateProfilePath)
module.exports=router;